### PR TITLE
Issue/28

### PR DESCRIPTION
**Pull request by titay2**
the final merge

### CODE REVIEW

**Comment by flyjwayur** [comment]
@titay2 Titay:D Thank you so much for all the effort. Does this mean all the files are merged? Or There are conflicts? Because the 'Merge pull request' button is not active yet. Is there anything that I can help? We can solve it together :D

**Comment by titay2** [comment]
@flyjwayur I am not sure what went wrong I am trying to figure out what is happening :/

**Comment by gr2m** [comment]
@titay2 usually that means that the branch you want to merge into (`gh-pages`) was updated since you started working on your `issue/28` branch. You can git pull `gh-pages` locally, then `git checkout issue/28` and then `git rebase gh-pages`. I just tried that and it shows some conflicts that you will need to resolve by hand, unfortunately 

I know this is frustrating, because this stuff is really hard :( But you both are getting the hang of it, and I’m here to help if you need me

**Comment by flyjwayur** [comment]
@gr2m @titay2 Thank you for the advice. If we want to reduce conflicts in the future, we can 'git pull' gh-pages first to update our local gh-pages and origin/gh-pages, before we create new branch(issue/num)? If it is, I guess we didn't know and missed this part. I'm often confused of local gh-pages, origin/gh-pages and remote gh-pages. Is there any way to solve this conflict together with Titay? I can also try to solve conflicts what you suggested above, even though the 'Merge pull request' is not activated?? :D

**Pull request closed without merging**
